libviper: always use "%s"-style format for printf()-style functions
`ncuses-6.3` added printf-style function attributes and now makes
it easier to catch cases when user input is used in palce of format
string when built with CFLAGS=-Werror=format-security:

    libviper/viper_msgbox.c:107:9:
      error: format not a string literal and no format arguments [-Werror=format-security]
      107 |         mvwprintw(WINDOW_FRAME(vwnd), height - 3, tmp, prompt);
          |         ^~~~~~~~~

Let's wrap all the missing places with "%s" format.